ARG targetplatform="linux/amd64"
FROM --platform="${targetplatform}" ubuntu:18.04

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    git \
    iputils-ping \
    libcurl4 \
    libicu60 \
    libunwind8 \
    netcat \
    libssl1.0 \
  && rm -rf /var/lib/apt/lists/*

# Tested with 'linux-x64' and 'linux-arm64' so far, but should also work with 'linux-arm' and 'rhel.6-x64'
ARG targetarch
ENV TARGETARCH="${targetarch:-linux-x64}"

# Downloading and installing Powershell for specified targetarch (linux-x64 if build-arg was not used)
RUN curl -L -o /tmp/powershell.tar.gz \
    "https://github.com/PowerShell/PowerShell/releases/download/v7.2.4/powershell-7.2.4-${TARGETARCH}.tar.gz" \
  && mkdir -p /opt/microsoft/powershell/7 \
  && tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7 \
  && chmod +x /opt/microsoft/powershell/7/pwsh \
  && ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# Install Pulumi-CLI
RUN curl -fsSL https://get.pulumi.com | sh \
  && ln -s /root/.pulumi/bin/pulumi /usr/bin/pulumi

# Install Python3.8
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.8 \
    python3.8-dev \
    python3.8-venv \
    python3-pip \
  && rm -rf /var/lib/apt/lists/*

# Install Azure-CLI
RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
  && rm -rf /var/lib/apt/lists/*

# Create Python3.8.0 tool directory and update pip
RUN python3.8 -m pip install --upgrade pip \
  && mkdir -p /azp/_work/_tool/Python/3.8.0 \
  && cd /azp/_work/_tool/Python/3.8.0 \
  && python3.8 -m venv x64 \
  && touch x64.complete

# Create Python3.6.9 tool directory and update pip
RUN apt-get update \
  && apt-get install -y --no-install-recommends python3-venv \
  && python3.6 -m pip install --upgrade pip \
  && mkdir -p /azp/_work/_tool/Python/3.6.9 \
  && cd /azp/_work/_tool/Python/3.6.9 \
  && python3.6 -m venv x64 \
  && touch x64.complete \
  && rm -rf /var/lib/apt/lists/*
  # && toolpath=$(python3 -V) \
  # && echo ${toolpath/ //} \
  # && mkdir -p ${toolpath/ //} \
  # && cd ${toolpath/ //} \

# clean tmp Folder
RUN rm -Rf /tmp/**

WORKDIR /azp
COPY ./start.sh .
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]
